# Site settings
title: Eight Chakras
site_url: "www.yoganosh.com"
url: "https://www.yoganosh.com"
version: 1.0
excerpt_separator: <!--more-->
fb_admins: "fb_admins"
fb_appid: "fb_appid"

baseurl: ""

# Build settings
permalink: "/story/:title/"
sass:
  sass_dir: _sass
  style: compressed
include: ['_pages']
exclude:
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock
  - less

# Markdown settings
markdown: kramdown
kramdown:
  auto_ids:       true
  auto_id_stripping:    true

gems:
  - jekyll-feed
  - jekyll-sitemap

# HTML Compression settings
#compress_html:
#  clippings: [ ]
#  blanklines: false
#  profile: false
